version: '3.8'

services:
  postgres:
    restart: always
    image: postgres:13.3
    environment:
      POSTGRES_DB: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'qwerty'
    ports:
      - '5432:5432'
    volumes:
      - ./_sql/:/docker-entrypoint-initdb.d/
      - ./.database/postgres/data:/var/lib/postgresql/data